### ISSUE TITLE
Demo-Page not showing Tiles

### ISSUE THREAD

**Issue by Robdebert** [joomla-framework/openstreetmap-api#2]
On http://extensions.joomla.org/profile/extension/maps-a-weather/maps-a-locations/osmodul i found the link to the demo-page: http://hof-ronig.de/

But all the tiles couldn't be loaded (see javascript-console). I think the custom-tile server ist just not reachable anymore.

**Comment by mbabker** [comment]
Hi there,

This repository isn't the source for that Joomla CMS extension; rather this is a standalone Joomla Framework library.  I'd suggest following the links in the listing to try and contact that extension's developer and let him know about this issue.
